<a href="https://colab.research.google.com/github/IbrahemAmar/Data-mining-and-Machine-Learning-/blob/main/lab2_ex1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
#import datasets
from sklearn import datasets
#matplotlib inline
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier

In [2]:
# vector distance
# Find the distance between vectors
def vecDist(vec1,vec2):
    vecDiff = vec1-vec2
    #compute the distance ("pitagoras")
    vecSqr =  np.square(vecDiff)
    vecSum =  np.sum(vecSqr)
    return np.sqrt(vecSum)

In [3]:
# plot data
# Plot the data with colored labels
def plotData(data, labels,fNames,col1,col2,labelsType):
    #plot the titles
    plt.title("The Iris Dataset " + labelsType +  " labels")
    plt.xlabel(fNames[col1])
    plt.ylabel(fNames[col2])
    # plot the data with different color for every label and size of 50 pixels
    myPlot = plt.scatter(data[:,col1],data[:,col2],c = labels, s=50)
    plt.legend(handles=myPlot.legend_elements()[0], labels=list(set(labels)))
    plt.show()

In [4]:
# split to train and test
# Load Iris dataset
Iris = datasets.load_iris()
data = Iris.data
labels = Iris.target+1 # true labeling
fNames = Iris.feature_names

In [5]:
samples = np.array([0,50,100])

In [ ]:
delta = 25

In [ ]:
# Split the data into test and train data
trainData = np.concatenate([data[samples[0]:samples[0]+delta],
                       data[samples[1]:samples[1]+delta],
                       data[samples[2]:samples[2]+delta]],axis=0)

trainLabels = np.concatenate([labels[samples[0]:samples[0]+delta],
                        labels[samples[1]:samples[1]+delta],
                        labels[samples[2]:samples[2]+delta]])

In [ ]:
samples+=25

In [ ]:
testData = np.concatenate([data[samples[0]:samples[0]+delta],
                      data[samples[1]:samples[1]+delta],
                      data[samples[2]:samples[2]+delta]],axis=0)

testLabels = np.concatenate([labels[samples[0]:samples[0]+delta],
                        labels[samples[1]:samples[1]+delta],
                        labels[samples[2]:samples[2]+delta]])

In [ ]:
# knn pridict sample
# Predicted a data sample using the KNN algorithm with k=1

# take a sample from the test group and predict its label type
testI = 50
testDataI=testData[testI,:]

In [ ]:
# Find the  distance between the selected sample and all the
# samples in the training group
dist = np.zeros(trainLabels.size)
for i,trainDataI in enumerate(trainData):
    dist[i] = vecDist(testDataI,trainDataI)

In [ ]:
# find the index of the train sample with the mininum distance
# to the selected sample
predictI = np.argmin(dist)
# get the label of the found sample
predictedLabel = trainLabels[predictI]
print("Sample:", testI, "predicted label:", predictedLabel, "true label",testLabels[testI])

In [ ]:
# built-in knn predict sample
# Use knn build in algorithm

# choose the number of neigbors
k=1
# prepare the knn model with the given k
knn = KNeighborsClassifier(n_neighbors=k)
# Build the knn model with the given data
knn.fit(trainData, trainLabels)

In [ ]:
# predict the given sample
predictI = knn.predict([testDataI])
print("Sample:", testI, "predicted label:", predictedLabel, "true label",testLabels[testI])

In [ ]:
# predict all the data in the test grpoup
predictedLabels = knn.predict(testData)

In [ ]:
# plot the samples in the test group with the true and the predicted labels
plotData(testData,testLabels,fNames,0,1,"true")
plotData(testData,predictedLabels,fNames,0,1,"predicted")

In [ ]:
plotData(testData,testLabels,fNames,2,3,"true")
plotData(testData,predictedLabels,fNames,2,3,"predicted")

#Independent work

###10.	Compose a training set of 90 flowers, 30 flowers of every type.

###11.	Compose a testing set of 60 flowers that are not in the training set.


In [6]:
delta = 30

In [7]:
# Split the data into test and train data
trainData = np.concatenate([data[samples[0]:samples[0]+delta],
                       data[samples[1]:samples[1]+delta],
                       data[samples[2]:samples[2]+delta]],axis=0)

trainLabels = np.concatenate([labels[samples[0]:samples[0]+delta],
                        labels[samples[1]:samples[1]+delta],
                        labels[samples[2]:samples[2]+delta]])

In [8]:
samples+=30
delta01=20

In [9]:
testData = np.concatenate([data[samples[0]:samples[0]+delta01],
                      data[samples[1]:samples[1]+delta01],
                      data[samples[2]:samples[2]+delta01]],axis=0)

testLabels = np.concatenate([labels[samples[0]:samples[0]+delta01],
                        labels[samples[1]:samples[1]+delta01],
                        labels[samples[2]:samples[2]+delta01]])

###12.	Find the KNN predicted labels of all the flowers in the test set using the minimum distance method and put them in a predicted vector.


In [10]:
# predicted labels for all test samples
predictedManual = np.zeros(testLabels.size, dtype=int)

for i, testData0 in enumerate(testData):
    best_dist = 1e9
    best_label = None

    # calculate distance to every training sample
    for j, trainData0 in enumerate(trainData):
        dis = vecDist(testData0, trainData0)
        if dis < best_dist:
            best_dist = dis
            best_label = trainLabels[j]

    predictedManual[i] = best_label

predictedManual


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 2,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

###13.	Compare the predicted test labels to the true test labels and find the number of errors (the number of labels that are wrongly predicted).

In [11]:
errorNumberManual = np.sum(predictedManual != testLabels)

In [12]:
errorNumberManual

np.int64(2)

###14.	Run the built-in KNN algorithm and compare it to your results. Did you get similar results? Explain your answer.

In [13]:
# built-in knn predict sample
# Use knn build in algorithm

# choose the number of neigbors
k=1
# prepare the knn model with the given k
knn = KNeighborsClassifier(n_neighbors=k)
# Build the knn model with the given data
knn.fit(trainData, trainLabels)

KNeighborsClassifier(n_neighbors=1)

In [14]:
# predict all the data in the test group
predictedLabels = knn.predict(testData)

In [15]:
predictedLabels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 2,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [16]:
testLabels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [17]:
errorNumber = np.sum(predictedLabels != testLabels)

In [18]:
errorNumber

np.int64(2)

###Did you get similar results? Explain your answer.

Yes we got similar results.. because 2 to 3