<a href="https://colab.research.google.com/github/IbrahemAmar/Data-mining-and-Machine-Learning-/blob/main/lab3_ex1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# import regular expressins packge
# import numbers package
import numpy as np
import re

In [4]:
#read file
def readFile(fileName):
    file = open(fileName,'r',encoding="cp437")
    fileText = ""
    for line in file:
        fileText += line
    return fileText

In [5]:
# preprocess text
def preProcess(text):
    # Remove non-letter chars
    text = re.sub("[^a-zA-Z ]"," ", text)
    # Change characters to lower
    text = text.lower()
    return text

In [6]:
def genReferenceWordList(texts,stopWords):
# concatenate the texts
    allText = ""
    for line in texts:
        allText += line
    # Generate a word list
    wordsList =  allText.split()
    # Generate a word set
    wordsSet =  set(wordsList)
    # Remove the stop words from the word list
    stopWordsList = stopWords.split()
    stopWordsSet = set(stopWordsList)
    refWordSet = wordsSet.difference(stopWordsSet)
    return list(refWordSet)

In [7]:
# vector distance
# find the distance between arrays
def vecDist(vec1,vec2):
    vecDiff = vec1-vec2
    # compute the distance ("pitagoras")
    vecSqr =  np.square(vecDiff)
    vecSum =  np.sum(vecSqr)
    return np.sqrt(vecSum)

In [8]:
# word frequency
def getWordFrequency(texts,dictList):
    dictSize = len(dictList)
    nTexts = len(texts)
    wordFreq = np.empty((nTexts,dictSize))
    for i in range(nTexts):
        print("text" + str(i))
        for j in range(dictSize):
            wordFreq[i,j] = texts[i].count(dictList[j])
    return wordFreq

In [9]:
books = []
#read  and preprocess files
books+= [readFile('DB.txt')]
books+= [readFile('Eliot.txt')]
books+= [readFile('HP.txt')]

In [10]:
window = 200000

In [11]:
# split every book into two parts
bookParts = []
for book in books:
    nParts = len(book)//window
    for i in range(nParts):
        bookParts += [book[i*window:(i+1)*window]]

In [12]:
# preprocess texts in book parts
texts = []
for text in bookParts:
    texts += [preProcess(text)]

In [13]:
# Read stop words file - words that can be removed
stopWords = readFile('stopwords_en.txt')

In [14]:
# generate reference word list
refList = genReferenceWordList(texts,stopWords)

In [15]:
# Find the frequency of the reference words in the files
wordFreq = getWordFrequency(texts,refList)

text0
text1
text2
text3
text4
text5


In [16]:
# find the distance matrix between the text files
# text distances
rows,colomns = wordFreq.shape

dist = np.zeros((rows,rows))
for i in range(rows):
    for j in range(rows):
        # calculate the distance between the frequency vectors
        dist[i,j] = round(vecDist(wordFreq[i],wordFreq[j]))

print("dist matrix = \n",dist)

dist matrix = 
 [[   0.  996. 2287. 2129. 2402. 2193.]
 [ 996.    0. 2154. 1990. 2316. 2079.]
 [2287. 2154.    0.  838. 2223. 2098.]
 [2129. 1990.  838.    0. 2005. 1914.]
 [2402. 2316. 2223. 2005.    0.  870.]
 [2193. 2079. 2098. 1914.  870.    0.]]
